insert into INSURANCE_POLICY (POLICY_ID,POLICY_NAME,POLICY_TENURE) values(101,'JEEVAN BEEMA',24);
insert into INSURANCE_POLICY (POLICY_ID,POLICY_NAME,POLICY_TENURE) values(102,'JEEVAN ANAND',6);
insert into INSURANCE_POLICY (POLICY_ID,POLICY_NAME,POLICY_TENURE) values(103,'PRUDENTIAL',5);
insert into INSURANCE_POLICY (POLICY_ID,POLICY_NAME,POLICY_TENURE) values(104,'LIFE INSURANCE',12);