insert into STOCK_PRICE(COMPANY_ID,COMPANY_NAME,COMPANY_PRICE) values(101,'HCL',750.25);
insert into STOCK_PRICE(COMPANY_ID,COMPANY_NAME,COMPANY_PRICE) values(102,'iNeuron',650.75);
insert into STOCK_PRICE(COMPANY_ID,COMPANY_NAME,COMPANY_PRICE) values(103,'Infosys',1350.50);
insert into STOCK_PRICE(COMPANY_ID,COMPANY_NAME,COMPANY_PRICE) values(104,'BHEL',450.10);